### ISSUE TITLE
Bioinformatics Training Calendar

### ISSUE THREAD

**Issue by kipkurui** [mbbu/Bioinformatics-Unit-Training#5]
Create a training calendar for 2023 and use this issue to track implementation. 

- [x] January: 
- [x] February:
- [x] March:
- [x] April
- [x] May
- [x] June
- [x] July
- [x] August
- [x] Sept

**Comment by kipkurui** [comment]
Hi Nehemiah. How far are we with this?

**Comment by NOngeso** [comment]
Will have a draft by COB friday

**Comment by kipkurui** [comment]
Quick follow-up on this. Please share what you have then I can refine it as needed.

**Comment by NOngeso** [comment]
Here is a draft: https://github.com/mbbu/Bioinformatics-Unit-Training/blob/master/2023_training_plan.md
